version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
 
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "Ecommerce"          
    ports:
      - "5432:5432"